name: "Pull Request Labeler"
on:
- pull_request

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: intoday87/labeler@main
      with:
        configuration-path: .github/branches.yml
        repo-token: "${{ secrets.GITHUB_TOKEN }}"